### ISSUE TITLE
running time issue in the discussion

### ISSUE THREAD

**Issue by kwea123** [gengshan-y/VCN#1]
You mentioned in the discussion of the paper: 

> The weakness of our current solution is that the FLOPS numbers are not directly transferable to the
running time due to CUDA kernel and hardware support.

Is it mainly due to the `corrf()` function which does `for` loops?
You also state in the readme that the `corr()` function can speed up inference, but how much precisely?
Finally, from other repos of optical flow I can find several implementations which compute the correlation without python for loops and support backward, e.g. [PWCNet](https://github.com/NVlabs/PWC-Net/tree/master/PyTorch/external_packages/correlation-pytorch-master), [IRR](https://github.com/visinf/irr/tree/master/models/correlation_package); how are their implementation different from yours?

**Comment by gengshan-y** [comment]
Hi, corr() reduces the running time by ~20ms. Please also refer to the updated readme for some analysis on why the current version is slow. 

When doing correlation, we keep the channel-wise feature products as-is (without summing them up), and use them (we refer to as multi-channel cost volumes in Sec.3.3) for later 4D filtering.
