### ISSUE TITLE
Upsampled Flow Coefficient

### ISSUE THREAD

**Issue by jytime** [gengshan-y/VCN#10]
Hi,

Thanks for your excellent work. I was wondering, what does the coefficient of the flow mean? For example, in VCN model, you times the upsample flow by 2. I may understand it. I think it means that when image size is enlarged by two times, the flow value should double. 
> up_flow6 = F.upsample(flow6, [im.size()[2]//32,im.size()[3]//32], mode='bilinear')*2

However, PWC-Net times the upsampled flow by 0.625 or 5.0, which seems to be weird:
> warp5 = self.warp5(c25, up_flow6*0.625)

I am confused about the actual meaning of this coefficient.  Any comment is welcome.

Best

**Comment by gengshan-y** [comment]
You're right about the flow upsampling operation in VCN. 

For PWCNet, I think they predict "flow divided by 20" at every scale. For example, at stride=4 scale, "the actual flow to be used for warping = predicted flow * 20 / 4 = predicted flow * 5". That's where 5.0 comes from.

**Comment by jytime** [comment]
Thanks a lot for your quick reply!
