### ISSUE TITLE
Unable to untar the pre-trained VCN model weights

### ISSUE THREAD

**Issue by pichuang1984** [gengshan-y/VCN#15]
Hi,

Thanks so much for open-sourcing your work! 

I am trying to load your pre-trained model weights from (https://drive.google.com/drive/folders/1mgadg50ti1QdwfAf6aR2v1pCx-ITsYfE?usp=sharing) but I am not able to untar the finetune_149999.tar from neither "chairs" or "kitti-ft-trainval". Below is the error message:

```
tar -xvf finetune_149999.tar
tar: Error opening archive: Unrecognized archive format
```

**Comment by gengshan-y** [comment]
Hi, don't need to untar it. You can just use the original .tar file. This confusing suffix is a [pytorch convention]( https://pytorch.org/tutorials/beginner/saving_loading_models.html).

**Comment by pichuang1984** [comment]
Ah thanks! I was under the impression that pytorch checkpoint often ends with *.pth.tar. Will close the issue.
