### ISSUE TITLE
Correlation in PWC-net

### ISSUE THREAD

**Issue by Guptajakala** [gengshan-y/VCN#17]
Hi, thanks for the great work! I have a question about your corr filter implementation in PWC-Net
https://github.com/gengshan-y/VCN/blob/eb816cbc7887fd81fd80f36311e95eaddcb16f62/models/PWCNet.py#L191

The original PWC-Net repo has another cuda implementation, could you confirm if your implementation does the same thing as the implementation from PWC-Net original repo?

**Comment by gengshan-y** [comment]
Yea, they should give the same output. corr() might be slower though.
