### ISSUE TITLE
the number of Training epoch

### ISSUE THREAD

**Issue by OreoChocolate** [gengshan-y/VCN#20]
Hi,

I'm trying to reproduce your results.
In the README.md, finetuning on KITTI, sintel needs 1000 epoch.

Is a model trained for 1000epochs to reproduce the results in the paper?

thx.

**Comment by gengshan-y** [comment]
Hi, in my experience, it takes 140k iterations, starting from the provided pre-trained model. Where does 1000 epochs come from?

**Comment by OreoChocolate** [comment]
In the README.md

> CUDA_VISIBLE_DEVICES=0,1 python main.py --maxdisp 256 --fac 1 --database /ssd/ --logname things-0 --savemodel /data/ptmodel/  --epochs 1000 --stage things --ngpus 2 --loadmodel ./weights/charis/finetune_141999.tar --retrain false

so I think pre-trained model must be trained during 1000epoch.

thank you.
