### ISSUE TITLE
How to eval on flyingthings?

### ISSUE THREAD

**Issue by Prinsphield** [gengshan-y/VCN#6]
I have noticed that there is a lack of implementation of this part. So I implement one by myself. But I found that there was a mismatch in the dimensions. The image size of flyingthings is 960 x 540. I guess the reason is that 540 is not divisible by 64. I wish for your help.

**Comment by gengshan-y** [comment]
You could try resizing the input image to a size divisible by 64,
see https://github.com/gengshan-y/VCN/blob/371505bf925f2228a4a419df3b0ae792057dafa2/submission.py#L149

and make sure to multiply the according ratio aftering resizing the prediction back:
https://github.com/gengshan-y/VCN/blob/371505bf925f2228a4a419df3b0ae792057dafa2/submission.py#L184
