### ISSUE TITLE
Evaluation on Sintel 

### ISSUE THREAD

**Issue by Prinsphield** [gengshan-y/VCN#7]
Hi, I have run the `submission.py` code for sintel dataset. However, here comes the error
```
No such file or directory: 'xxxx/datasets/rob_flow/training/image_2/'
```

Could you please share the directory structure of the sintel dataset. I just download from the official website. Here is my structure.
```
├── bundler
│   ├── linux-x64
│   ├── osx
│   ├── README_BUNDLER.txt
│   └── win
├── flow_code
│   ├── C
│   └── MATLAB
├── README.txt
├── test
│   ├── clean
│   └── final
└── training
    ├── albedo
    ├── clean
    ├── final
    ├── flow
    ├── flow_viz
    ├── invalid
    └── occlusions
```
There is no `image_2` folder under the `training` dir.

**Comment by gengshan-y** [comment]
Hi, here is mine:
├── bundler
│   ├── linux-x64
│   ├── osx
│   └── win
├── metadata
├── test
│   └── image_2
└── training
    ├── flow_occ
    └── image_2

As I mentioned in the readme, the fine-tuning dataset for his code base can be downloaded [here](http://www.cvlibs.net:3000/ageiger/rob_devkit/src/flow/flow):, which has slightly different organization of the images.
